### ISSUE TITLE
Support for php attributes

### ISSUE THREAD

**Issue by arendjantetteroo** [iwink/gitlab-webhook-bundle#7]
**Is your feature request related to a problem? Please describe.**
I tried installing your bundle on a symfony 6 project that no longer uses doctrine/annotations 1, but is on doctrine/annotations 2. 

**Describe the solution you'd like**
Any plans to update to support php attributes? 

I can spent some time upgrading, i'm wondering if you are open to a PR that would move to attributes only (and so a new major is needed) or want to support both in the meantime?

**Comment by doekenorg** [comment]
Hey @arendjantetteroo .

Yes we are planning on doing this 'soon tm'. Your PR is very much appreciated. When I'm back at work I'll check it out. 

For the depreciation, the #ReturnTypeWillChange annotation should suffice for now.

Edit: I want to prevent breaking changes for now. But the next major will contain the return type.

Thanks

**Comment by arendjantetteroo** [comment]
@doekenorg i haven't gotten far yet with actually using this bundle unfortunately, see #10

**Comment by arendjantetteroo** [comment]
I've migrated to use the symfony webhook component instead of this bundle, so i can migrate to symfony 7. 

I will close this issue.
